language: python
matrix:
  include:
    # - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install pytest-cov
  - pip install codecov
  - pip install .
script: pytest --cov=resteasycli && codecov && bash tests/e2e/run_demo.sh && python tests/e2e/execute_all_commands.py
