language: python
matrix:
  include:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install pytest-cov
  - pip install codecov
  - pip install .
  - recli init -f
script:
  - pytest --cov=resteasycli --cov-report term
  - bash tests/e2e/run_demo.sh
  - python tests/e2e/execute_all_commands.py
after_success:
  - codecov
